import { Question } from "../types";
export const CHAIN_ID = 80001;
export const CHAIN_NAME = "mumbai";
export const TEST_NFT_CONTRACT_ADDRESS =
  "0xe5b4d6b5f37cae9dc4c7384cd97038cd0573d7d2"; // Strxngers
export const FORM_COLLECTION_FACTORY_CONTRACT_ADDRESS =
  "0xEBed7538E8cc636F3FbaCEE289Aacb2Ef959AbA2";

export const AGE_QUESTION: Question = {
  id: "2f633cdd1181d42a9c7ae9a889362ff7",
  questionBody: "What's your age range?",
  questionType: "single_choice",
  ratingMax: 5,
  options: [
    "Under 21",
    "Between 21 and 30",
    "Between 31 and 40",
    "Between 41 and 50",
    "Over 50",
    "Prefer not to respond",
  ],
};

export const GENDER_QUESTION: Question = {
  id: "c31248e78aced0c36320b2f13a8a7891",
  questionBody: "What's your gender?",
  questionType: "single_choice",
  ratingMax: 5,
  options: [
    "Male",
    "Female",
    "Transgender",
    "Non-binary / non-conforming",
    "Intersex",
    "Other",
    "Prefer not to say",
  ],
};

export const COUNTRY_QUESTION: Question = {
  id: "5ca2aa845c8cd5ace6b016841f100d82",
  questionBody: "In what country are you based?",
  questionType: "single_choice_dropdown",
  ratingMax: 5,
  options: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua & Deps",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo {Democratic Rep}",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland {Republic}",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar, {Burma}",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "St Kitts & Nevis",
    "St Lucia",
    "Saint Vincent & the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
};

export const ETHNICITY_QUESTION: Question = {
  id: "8e9c7a86c8295244c2f50e1049023b1b",
  questionBody: "What's your ethnicity?",
  questionType: "single_choice_dropdown",
  ratingMax: 5,
  options: [
    "Hispanic",
    "White alone, non-Hispanic",
    "Black or African American alone, non-Hispanic",
    "American Indian and Alaska Native alone, non-Hispanic",
    "Asian alone, non-Hispanic",
    "Native Hawaiian and Other Pacific Islander alone, non-Hispanic",
    "Some Other Race alone, non-Hispanic",
    "Multiracial, non-Hispanic",
    "Prefer not to say",
    "Other",
  ],
};

export const INDUSTRY_QUESTION: Question = {
  id: "c570503c6bd0a44eb7ab38365ca83ced",
  questionBody: "What's your occupation's industry?",
  questionType: "single_choice",
  ratingMax: 5,
  options: [
    "Arts and entertainment",
    "Business administration",
    "Industrial and manufacturing",
    "Law enforcement and armed forces",
    "Science and technology",
    "Others",
  ],
};

export const RATING_QUESTION: Question = {
  id: "3970500c6bd0a44ed7ab383650a33abc",
  questionBody: "How do you like decensus?",
  questionType: "rating",
  ratingMax: 5,
  options: [],
};

export const PREDEFINED_QUESTIONS: Question[] = [
  AGE_QUESTION,
  GENDER_QUESTION,
  COUNTRY_QUESTION,
  ETHNICITY_QUESTION,
  INDUSTRY_QUESTION,
  RATING_QUESTION,
];
